Repository nextcloud/impersonate, pull requests merged in 2018-03, with the labels that each got.

#28 Allow group admins to impersonate
  appinfo/app.php
  appinfo/info.xml
  js/admin_settings.js
  js/impersonate.js
  lib/AdminSettings.php
  lib/Controller/SettingsController.php
  templates/admin_settings.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 3. to review, backport-request, enhancement, security

#33 [stable13] Clean up template generation and bring back translation
  js/impersonate.js
Labels: 3. to review, bug

#35 [12/13] Allow group admins to impersonate
  appinfo/app.php
  appinfo/info.xml
  js/admin_settings.js
  js/impersonate.js
  lib/AdminSettings.php
  lib/Controller/SettingsController.php
  templates/admin_settings.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 3. to review, enhancement

#36 prepare 1.0.3 release
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3. to review

#38 fix ci for stable13
  .drone.yml
  appinfo/info.xml
Labels: 3. to review
