Repository nextcloud/impersonate, pull requests merged in 2018-02, with the labels that each got.

#26 Move transifex config for updated l10n script
  .tx/config
  Makefile
Labels: enhancement

#27 Clean up template generation and bring back translation
  js/impersonate.js
Labels: 3. to review, backport-request, bug

#30 Test with PHPUnit 6.5
  .drone.yml
  tests/unit/bootstrap.php
Labels: 3. to review, bug
