Repository nextcloud/impersonate, pull requests merged in 2020-05, with the labels that each got.

#97 users shall not impersonate themselves
  lib/Controller/SettingsController.php
Labels: 3. to review, bug

#101 adjust krankerl config
  .nextcloudignore
  krankerl.toml
Labels: backport-request

#106 l10n: Text string correction
  lib/Controller/SettingsController.php
Labels: design
