Repository nextcloud/impersonate, pull requests merged in 2022-11, with the labels that each got.

#169 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#170 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#176 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#181 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#177 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#174 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#172 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#167 Migrate to nextcloud/OCP package in stable23
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  composer.lock
Labels: 4. to release
