Repository nextcloud/impersonate, pull requests merged in 2023-11, with the labels that each got.

#236 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#237 fix(frontend): fix determining user id
  js/impersonate.js
Labels: 3. to review, bug

#232 Add instructions/caveats to README
  README.md
Labels: 3. to review, enhancement, feedback-requested

#238 chore(meta): changelog for v1.15.0
  CHANGELOG.md
Labels: 4. to release
