Repository nextcloud/impersonate, pull requests merged in 2023-05, with the labels that each got.

#207 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#211 fix: impersonate logout
  js/impersonate_logout.js
Labels: 3. to review, backport-request, bug

#215 chore: remove files from packaging
  .nextcloudignore
Labels: backport-request

#220 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#219 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
