Repository nextcloud/impersonate, pull requests merged in 2023-04, with the labels that each got.

#205 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#206 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#201 chore(CI): Adjust testing matrix for Nextcloud 26 on stable26
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 4. to release

#202 chore: Add Nextcloud 27 support on master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
Labels: 3. to review
