Repository nextcloud/impersonate, pull requests merged in 2023-02, with the labels that each got.

#189 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#192 chore(CI): Update master php testing versions and workflow templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/AdminSettings.php
  lib/AppInfo/Application.php
  lib/Listener/BeforeTemplateRenderedListener.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 4. to release

#191 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#190 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#194 fix unexpected parameter to callback
  js/impersonate.js
Labels: 4. to release, backport-request, bug

#180 Add ImpersonateEvents for SnappyMail (and others)
  js/impersonate_logout.js
  lib/Controller/LogoutController.php
  lib/Controller/SettingsController.php
  lib/Events/AImpersonateEvent.php
  lib/Events/BeginImpersonateEvent.php
  lib/Events/EndImpersonateEvent.php
  tests/phpunit.xml
  tests/unit/Controller/SettingsControllerTest.php
Labels: 3. to review, enhancement

#200 1.13.0
  CHANGELOG.md
Labels: 3. to review

#198 v1.11.1
  .github/workflows/phpunit-pgsql.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: 4. to release
