Repository nextcloud/impersonate, pull requests merged in 2024-07, with the labels that each got.

#313 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#312 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#314 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#321 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#318 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#322 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#323 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#324 build(Release): 1.17.0
  .github/workflows/appstore-build-publish.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#325 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#326 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#327 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#328 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
