Repository nextcloud/impersonate, pull requests merged in 2024-04, with the labels that each got.

#268 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#242 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.lock
  lib/Controller/LogoutController.php
  lib/Controller/SettingsController.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 2. developing, dependencies, automated, feedback-requested

#282 [stable28] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#281 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#279 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#283 [stable27] fix platform req and update deps
  composer.json
  composer.lock
  lib/Controller/LogoutController.php
  lib/Controller/SettingsController.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 3. to review, dependencies

#286 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#285 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#284 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#287 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#289 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#288 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies
