Repository nextcloud/impersonate, pull requests merged in 2024-03, with the labels that each got.

#250 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#255 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#259 use promoted arguments, switching to IAppConfig
  lib/Controller/LogoutController.php
  lib/Controller/SettingsController.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 3. to review, technical debt

#264 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#261 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies
